name: Write key to static file

on:
  repository_dispatch: # Allows manual execution
   inputs:
      locationID:
        description: 'Location'
        required: true
        default: 'yfyIrXrm61r57rx3ex4N'
      key:
        description: 'Access key'
        required: true
        default: '1234'

jobs:
  write-file:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Create staticTokens directory
        run: mkdir -p ./staticTokens

      - name: Write to file
        run: echo "${{ github.event.inputs.key }}" > "./staticTokens/${{ github.event.inputs.locationID }}"

      - name: Commit changes
        run: |
          git config --local user.name "github-actions"
          git config --local user.email "github-actions@github.com"
          git add "./staticTokens/${{ github.event.inputs.locationID }}"
          git commit -m "Add key to ./staticTokens/${{ github.event.inputs.locationID }}"
          git push
