name: Write key to static file

on:
  workflow_dispatch: # Allows manual execution
   inputs:
      locationID:
        description: 'Location'
        required: true
        default: 'yfyIrXrm61r57rx3ex4N'
      key:
        description: 'Access key'
        required: true
        default: '1234'

jobs:
  write-file:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Create staticKeys directory
        run: mkdir -p ./staticKeys

      - name: Write to file
        run: echo "${{ github.event.inputs.key }}" > "./staticKeys/${{ github.event.inputs.locationID }}"

      - name: Commit changes
        run: |
          git config --local user.name "github-actions"
          git config --local user.email "github-actions@github.com"
          git add "./staticKeys/${{ github.event.inputs.locationID }}"
          git commit -m "Add key to ./staticKeys/${{ github.event.inputs.locationID }}"
          git push
